"""
Django settings for pepdb project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from dotenv import load_dotenv

from .common_settings import *

load_dotenv()


def getenv_bool(key, default=False):
    '''Generate a boolean value from env

    Values 1, true and yes are considered `True`, case-insensitively.
    '''
    value = os.getenv(key)
    if value is None:
        return default
    result = value.lower() in {'1', 'true', 'yes'}
    return result


CONFIG_PREFIX = "PEPDB_"

SECRET_KEY = os.environ[CONFIG_PREFIX + 'SECRET_KEY']
DEBUG = getenv_bool(CONFIG_PREFIX + 'DEBUG', False)

hosts = os.environ.get(CONFIG_PREFIX + "ALLOWED_HOSTS")
ALLOWED_HOSTS = hosts.split(",") if hosts is not None else []

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
default_db = {
    "ENGINE": os.getenv(CONFIG_PREFIX + "DB_ENGINE", "django.db.backends.sqlite3"),
}

_is_sqlite = default_db["ENGINE"] == "django.db.backends.sqlite3"
default_db["NAME"] = os.getenv(
    CONFIG_PREFIX + "DB_NAME",
    str(BASE_DIR / 'pepdb.sqlite3') if _is_sqlite else ""
)

for key in ("USER", "PASSWORD", "HOST", "PORT"):
    config_key = f"{CONFIG_PREFIX}DB_{key}"
    if config_key in os.environ:
        default_db[key] = os.environ[config_key]

DATABASES = {'default': default_db}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
LANGUAGE_CODE = os.getenv(CONFIG_PREFIX + 'LANGUAGE_CODE', 'de-de')
TIME_ZONE = os.getenv(CONFIG_PREFIX + 'TIME_ZONE', 'Europe/Berlin')
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email settings
# https://docs.djangoproject.com/en/4.0/ref/settings/#email-backend
# by default, just print to console
backend = os.getenv(CONFIG_PREFIX + 'EMAIL_BACKEND', 'console')
EMAIL_BACKEND = f'django.core.mail.backends.{backend}.EmailBackend'
if backend == 'smtp':
    EMAIL_HOST = os.environ[CONFIG_PREFIX + 'EMAIL_HOST']
    EMAIL_PORT = os.environ[CONFIG_PREFIX + 'EMAIL_PORT']
    EMAIL_HOST_USER = os.environ[CONFIG_PREFIX + 'EMAIL_USER']
    EMAIL_HOST_PASSWORD = os.environ[CONFIG_PREFIX + 'EMAIL_PASSWORD']
    EMAIL_USE_TLS = getenv_bool(CONFIG_PREFIX + 'EMAIL_USE_TLS', False)
    EMAIL_USE_SSL = getenv_bool(CONFIG_PREFIX + 'EMAIL_USE_SSL', False)

