"""empty message

Revision ID: 288c44807361
Revises: 392917c0d63f
Create Date: 2020-08-18 12:38:16.331163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "288c44807361"
down_revision = "392917c0d63f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # need to use batch operations to make it also work with sqlite
    # see https://alembic.sqlalchemy.org/en/latest/batch.html
    with op.batch_alter_table("event_registration") as batch_op:
        batch_op.alter_column("event_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("person_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("status", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_registration") as batch_op:
        batch_op.alter_column("status", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("person_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("event_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
