"""Add shortlink to event

Revision ID: 66b173ff9a64
Revises: 94cbf12be25a
Create Date: 2023-01-20 23:33:07.814569

"""
from alembic import op
import sqlalchemy as sa
from urllib.parse import quote

# revision identifiers, used by Alembic.
revision = "66b173ff9a64"
down_revision = "94cbf12be25a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("shortlink", sa.Text(), nullable=True, default=sa.null())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_column("shortlink")

    # ### end Alembic commands ###
