"""Add tu_status field to person and TUStatus table

Revision ID: 6cfe97168561
Revises: 02fcfdcb4b37
Create Date: 2021-01-24 13:08:53.956243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfe97168561'
down_revision = '02fcfdcb4b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    con = op.get_bind()
    if con.engine.name == 'sqlite':
        con.execute('PRAGMA foreign_keys = OFF;')

    op.create_table('tu_status',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_tu_status'))
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tu_status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_person_tu_status_id_tu_status'), 'tu_status', ['tu_status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_person_tu_status_id_tu_status'), type_='foreignkey')
        batch_op.drop_column('tu_status_id')

    op.drop_table('tu_status')
    # ### end Alembic commands ###
