"""Increase length of password_hash field

Revision ID: 742e6adb504c
Revises: 0151da823114
Create Date: 2024-01-19 12:51:21.629225

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "742e6adb504c"
down_revision = "0151da823114"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=256),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.String(length=256),
            type_=sa.VARCHAR(length=128),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
