"""Rename status to status_name to enable relationship

Revision ID: 94cbf12be25a
Revises: f87786c0cd2d
Create Date: 2022-04-23 15:59:34.763758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "94cbf12be25a"
down_revision = "f87786c0cd2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_registration", schema=None) as batch_op:
        batch_op.alter_column("status", new_column_name="status_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_registration", schema=None) as batch_op:
        batch_op.alter_column("status_name", new_column_name="status")
    # ### end Alembic commands ###
