"""empty message

Revision ID: bdd12eeb872b
Revises: c78f3c217703
Create Date: 2018-11-07 22:29:38.790110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd12eeb872b'
down_revision = 'c78f3c217703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('applied_for_mship', sa.Boolean(), nullable=True))
    op.drop_column('person', 'member_approved')
    op.alter_column('user', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('person', sa.Column('member_approved', sa.BOOLEAN(), nullable=True))
    op.drop_column('person', 'applied_for_mship')
    # ### end Alembic commands ###
