"""add membership type

Revision ID: f87786c0cd2d
Revises: 6cfe97168561
Create Date: 2021-01-24 15:07:09.117419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f87786c0cd2d"
down_revision = "6cfe97168561"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    con = op.get_bind()
    if con.engine.name == "sqlite":
        con.execute("PRAGMA foreign_keys = OFF;")
    op.create_table(
        "membership_type",
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_type")),
    )
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.add_column(sa.Column("membership_type_id", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_person_membership_type_id_membership_type"),
            "membership_type",
            ["membership_type_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_person_membership_type_id_membership_type"),
            type_="foreignkey",
        )
        batch_op.drop_column("membership_type_id")

    op.drop_table("membership_type")
    # ### end Alembic commands ###
