"""Add shortlink to event

Revision ID: fb89b8b18838
Revises: 94cbf12be25a
Create Date: 2023-01-21 16:39:59.649072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb89b8b18838'
down_revision = '94cbf12be25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shortlink', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_event_shortlink'), ['shortlink'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_event_shortlink'), type_='unique')
        batch_op.drop_column('shortlink')

    # ### end Alembic commands ###
